version: "3.9"

services:
  bedrock-rag-chatbot:
    build: .
    container_name: bedrock-rag-chatbot
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/application